extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_ground_lights;
extern Lights1 castle_grounds_dl_floor_lights;
extern Lights1 castle_grounds_dl_slippery_lights;
extern Lights1 castle_grounds_dl_water_001_layer5_area1_lights;
extern u8 castle_grounds_dl_rocktextso_rgba16[];
extern u8 castle_grounds_dl_testwater_ia8[];
extern Vtx castle_grounds_dl_Cube_mesh_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_mesh_vtx_0[160];
extern Gfx castle_grounds_dl_Cube_mesh_tri_0[];
extern Vtx castle_grounds_dl_Cube_001_mesh_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_001_mesh_vtx_0[60];
extern Gfx castle_grounds_dl_Cube_001_mesh_tri_0[];
extern Vtx castle_grounds_dl_Cube_001_mesh_vtx_1[8];
extern Gfx castle_grounds_dl_Cube_001_mesh_tri_1[];
extern Vtx castle_grounds_dl_loop_mesh_vtx_cull[8];
extern Vtx castle_grounds_dl_loop_mesh_vtx_0[228];
extern Gfx castle_grounds_dl_loop_mesh_tri_0[];
extern Vtx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Gfx mat_castle_grounds_dl_ground[];
extern Gfx mat_castle_grounds_dl_floor[];
extern Gfx mat_castle_grounds_dl_slippery[];
extern Gfx mat_castle_grounds_dl_water_001_layer5_area1[];
extern Gfx mat_revert_castle_grounds_dl_water_001_layer5_area1[];
extern Gfx castle_grounds_dl_Cube_mesh[];
extern Gfx castle_grounds_dl_Cube_001_mesh[];
extern Gfx castle_grounds_dl_loop_mesh[];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
